/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.t2._maua_tti101_t2_sistema_academico.telas;

import br.maua.t2._maua_tti101_t2_sistema_academico.db.UsuarioDAO;
import br.maua.t2._maua_tti101_t2_sistema_academico.modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author luisa
 */
public class CadastroTurmaTela extends javax.swing.JFrame {

    /**
     * Creates new form CadastroTurmaTela
     */
    public CadastroTurmaTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        senhaButton = new javax.swing.JPasswordField();
        nomeParaCadastroButton = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(610, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        okButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);
        okButton.setBounds(60, 270, 210, 70);

        senhaButton.setToolTipText("");
        senhaButton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Senha:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        senhaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(senhaButton);
        senhaButton.setBounds(50, 120, 450, 80);

        nomeParaCadastroButton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Nome para cadastro:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        nomeParaCadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeParaCadastroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nomeParaCadastroButton);
        nomeParaCadastroButton.setBounds(50, 20, 450, 81);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(27, 330, 100, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/turiminha semear logo tela cadastro.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 200, 190, 180);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela rosa.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-3, -20, 610, 470);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 270, 38, 16);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(440, 320, 38, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        Usuario.Fase1 = false;
        Usuario.Fase2 = false;
        Usuario.Fase3 = false;
        Usuario.Fase4 = false;
        Usuario.pontuacao = 1000;
      try{
        //1. pegar o login digitado pelo usuario
        var login = nomeParaCadastroButton.getText();
        //2. pegar a senha digitada pelo usuario
        var senha = new String(senhaButton.getPassword());
        var usuario = new Usuario();//cria o usuario no pc
        usuario.setLogin(login);
        usuario.setSenha(senha);
        var dao = new UsuarioDAO();//cria usuario de conexao
        dao.cadastrar(usuario);//coloca no bd
        if (dao.verificaProfessor(usuario)){
                dispose();
                new PontuacaoProfessor().setVisible(true);
            } 
            else{
                dispose();
                new TelaFasess().setVisible(true);
            }
            
      }
      catch(Exception e){
            System.out.println(e);
      }

    }//GEN-LAST:event_okButtonActionPerformed

    private void nomeParaCadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeParaCadastroButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeParaCadastroButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTurmaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTurmaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTurmaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTurmaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTurmaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nomeParaCadastroButton;
    private javax.swing.JButton okButton;
    private javax.swing.JPasswordField senhaButton;
    // End of variables declaration//GEN-END:variables
}
