/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.t2._maua_tti101_t2_sistema_academico.telas;

import br.maua.t2._maua_tti101_t2_sistema_academico.modelo.Usuario;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author luisa
 */
public class Fase3 extends javax.swing.JFrame{
int selecionado = -1; 
boolean peixe = false;//0
boolean abelha = false;
boolean leao = false;
boolean macaco = false;
boolean colmeia = false;
boolean mar = false;
boolean floresta = false;
boolean selva = false;
public void verificar_estado(){
    if (peixe) {
        botaoPeixeButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoPeixeButton.setEnabled(false);
    }
    if (abelha) {
        botaoAbelhaButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoAbelhaButton.setEnabled(false);
    }
    if (leao) {
        botaoLeaoButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoLeaoButton.setEnabled(false);
    }
    if (mar) {
        botaoMarButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoMarButton.setEnabled(false);
    }
    if (selva) {
        botaoSelvaButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoSelvaButton.setEnabled(false);
    }
    if (macaco) {
        botaoMacacoButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoMacacoButton.setEnabled(false);
    }
    if (floresta) {
        botaoFlorestaButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoFlorestaButton.setEnabled(false);
    }
    if (colmeia) {
        botaoColmeiaButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoColmeiaButton.setEnabled(false);
    }
}
public void verifica_fase(){
    if ((peixe && !mar) || (abelha && !colmeia)|| (leao && !floresta) || (macaco && !selva)) {
        Usuario.pontuacao = Usuario.pontuacao - 25;
    }
}
    /**
     * Creates new form Fase3
     */
    public Fase3(){
        initComponents();       
}
    private boolean avaliarSelecionado(int valor){
        
        if (selecionado == -1){
            selecionado = valor;
            return false;
        }
        //este primeiro if está verificando se ele foi selecionado, e apenas ele.
        else if (valor %4 == selecionado %4 && valor != selecionado){
            return true;
        //este if verifica se os dois valores lógicos são iguais(selecionado e valor atual). caso sim, o valor ficará verdadeiro.
        }
        else {
            selecionado = -1;
            return false;
        }
        //se o segundo botão for selecionado errado, ele volta a lógica dos botões para o estado inicial.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoMacacoButton = new javax.swing.JToggleButton();
        botaoLeaoButton = new javax.swing.JToggleButton();
        botaoSelvaButton = new javax.swing.JToggleButton();
        botaoPeixeButton = new javax.swing.JToggleButton();
        botaoColmeiaButton = new javax.swing.JToggleButton();
        botaoFlorestaButton = new javax.swing.JToggleButton();
        botaoMarButton = new javax.swing.JToggleButton();
        botaoAbelhaButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botaoMacacoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/macaco.png"))); // NOI18N
        botaoMacacoButton.setText("jToggleButton1");
        botaoMacacoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMacacoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMacacoButton);
        botaoMacacoButton.setBounds(460, 80, 129, 123);

        botaoLeaoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/leao.png"))); // NOI18N
        botaoLeaoButton.setText("jToggleButton1");
        botaoLeaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLeaoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoLeaoButton);
        botaoLeaoButton.setBounds(310, 80, 129, 123);

        botaoSelvaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/selva.png"))); // NOI18N
        botaoSelvaButton.setText("jToggleButton1");
        botaoSelvaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSelvaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSelvaButton);
        botaoSelvaButton.setBounds(10, 220, 129, 122);

        botaoPeixeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/peixe.png"))); // NOI18N
        botaoPeixeButton.setText("jToggleButton1");
        botaoPeixeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPeixeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoPeixeButton);
        botaoPeixeButton.setBounds(10, 80, 129, 122);

        botaoColmeiaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/colmeia.png"))); // NOI18N
        botaoColmeiaButton.setText("jToggleButton1");
        botaoColmeiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoColmeiaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoColmeiaButton);
        botaoColmeiaButton.setBounds(460, 220, 129, 118);

        botaoFlorestaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arvore.png"))); // NOI18N
        botaoFlorestaButton.setText("jToggleButton1");
        botaoFlorestaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFlorestaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoFlorestaButton);
        botaoFlorestaButton.setBounds(310, 220, 129, 122);

        botaoMarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mar.png"))); // NOI18N
        botaoMarButton.setText("jToggleButton1");
        botaoMarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMarButton);
        botaoMarButton.setBounds(160, 220, 129, 122);

        botaoAbelhaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abelha.png"))); // NOI18N
        botaoAbelhaButton.setText("jToggleButton1");
        botaoAbelhaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAbelhaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAbelhaButton);
        botaoAbelhaButton.setBounds(160, 80, 129, 122);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/branco fundo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMacacoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMacacoButtonActionPerformed
        //macaco
        int valor = 3;
        if (!macaco && !floresta && avaliarSelecionado(valor)){
            macaco = true;
            floresta = true;
            verificar_estado();
        } 
        verifica_fase();
    }//GEN-LAST:event_botaoMacacoButtonActionPerformed

    private void botaoLeaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLeaoButtonActionPerformed
        //leao
        int valor = 2;
        if (!leao && !selva && avaliarSelecionado(valor)){
            leao = true;
            selva = true;
            verificar_estado();
        }  
        verifica_fase();
    }//GEN-LAST:event_botaoLeaoButtonActionPerformed

    private void botaoSelvaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSelvaButtonActionPerformed
        //selva
        int valor = 6;
        if (!leao && !selva && avaliarSelecionado(valor)){
            leao = true;
            selva = true;
            verificar_estado();
        }   
        verifica_fase();
    }//GEN-LAST:event_botaoSelvaButtonActionPerformed

    private void botaoPeixeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPeixeButtonActionPerformed
        //peixe
        int valor = 0;
        if (!peixe && !mar && avaliarSelecionado(valor)){
            peixe = true;
            mar = true;
            verificar_estado();       
        }    
        verifica_fase();
    }//GEN-LAST:event_botaoPeixeButtonActionPerformed

    private void botaoColmeiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoColmeiaButtonActionPerformed
        //colmeia
        int valor = 5;
        if (!colmeia && !abelha && avaliarSelecionado(valor)){
            colmeia = true;
            abelha = true;
            verificar_estado(); 
        }  
        verifica_fase();
    }//GEN-LAST:event_botaoColmeiaButtonActionPerformed

    private void botaoFlorestaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFlorestaButtonActionPerformed
        //floresta
        int valor = 7;
        if (!macaco && !floresta && avaliarSelecionado(valor)){
            macaco = true;
            floresta = true;
            verificar_estado();
        }  
        verifica_fase();
    }//GEN-LAST:event_botaoFlorestaButtonActionPerformed

    private void botaoMarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMarButtonActionPerformed
        //mar
        int valor = 4;
        if (!peixe && !mar && avaliarSelecionado(valor)){
            peixe = true;
            mar = true;
            verificar_estado(); 
        } 
        verifica_fase();
    }//GEN-LAST:event_botaoMarButtonActionPerformed

    private void botaoAbelhaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAbelhaButtonActionPerformed
        //abelha
        int valor = 1;
        if (!colmeia && !abelha && avaliarSelecionado(valor)){
            colmeia = true;
            abelha = true;
            verificar_estado();
        }
        verifica_fase();
    }//GEN-LAST:event_botaoAbelhaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fase3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoAbelhaButton;
    private javax.swing.JToggleButton botaoColmeiaButton;
    private javax.swing.JToggleButton botaoFlorestaButton;
    private javax.swing.JToggleButton botaoLeaoButton;
    private javax.swing.JToggleButton botaoMacacoButton;
    private javax.swing.JToggleButton botaoMarButton;
    private javax.swing.JToggleButton botaoPeixeButton;
    private javax.swing.JToggleButton botaoSelvaButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}

