/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.t2._maua_tti101_t2_sistema_academico.telas;

import br.maua.t2._maua_tti101_t2_sistema_academico.modelo.Usuario;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author luisa
 */
public class Fase1 extends javax.swing.JFrame {

public void verifica_fase(){
    if (!botãoVermelhoButton.isEnabled() & !botãoVerdeButton.isEnabled() & !botãoAmareloButton.isEnabled() & !botãoAzulButton.isEnabled() ) {
        if (!Usuario.Fase2) {
            this.dispose();
            new Fase2().setVisible(true);
        } else if (!Usuario.Fase3) {
            this.dispose();
            new Fase3().setVisible(true);
        } else if (!Usuario.Fase4) {
            this.dispose();
            new Fase4().setVisible(true);
        } else {
            this.dispose();
            new PontuacaoTela().setVisible(true);
        }
    }
}
    /**
     * Creates new form Fase1
     */
    public Fase1() {
        initComponents();
    }

    /**
     * This me
     * thod is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botãoVermelhoButton = new javax.swing.JToggleButton();
        botãoVerdeButton = new javax.swing.JToggleButton();
        botãoAzulButton = new javax.swing.JToggleButton();
        botãoAmareloButton = new javax.swing.JToggleButton();
        botãoPlantaButton = new javax.swing.JToggleButton();
        botãoMorangoButton = new javax.swing.JToggleButton();
        botãoNuvemButton = new javax.swing.JToggleButton();
        botãoBananaButton = new javax.swing.JToggleButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botãoVermelhoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vermelho.png"))); // NOI18N
        botãoVermelhoButton.setText("jToggleButton1");
        botãoVermelhoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoVermelhoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botãoVermelhoButton);
        botãoVermelhoButton.setBounds(450, 70, 129, 122);

        botãoVerdeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/verde.png"))); // NOI18N
        botãoVerdeButton.setText("jToggleButton1");
        botãoVerdeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoVerdeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botãoVerdeButton);
        botãoVerdeButton.setBounds(310, 70, 129, 122);

        botãoAzulButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/azul.png"))); // NOI18N
        botãoAzulButton.setText("jToggleButton1");
        botãoAzulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoAzulButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botãoAzulButton);
        botãoAzulButton.setBounds(170, 70, 129, 122);

        botãoAmareloButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/amarelo.png"))); // NOI18N
        botãoAmareloButton.setText("jToggleButton1");
        botãoAmareloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoAmareloButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botãoAmareloButton);
        botãoAmareloButton.setBounds(30, 70, 129, 122);

        botãoPlantaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/planta.png"))); // NOI18N
        botãoPlantaButton.setText("jToggleButton1");
        botãoPlantaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoPlantaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botãoPlantaButton);
        botãoPlantaButton.setBounds(30, 220, 129, 122);

        botãoMorangoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/m2.png"))); // NOI18N
        botãoMorangoButton.setText("jToggleButton1");
        botãoMorangoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoMorangoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botãoMorangoButton);
        botãoMorangoButton.setBounds(170, 220, 129, 122);

        botãoNuvemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nuvem.png"))); // NOI18N
        botãoNuvemButton.setText("jToggleButton1");
        botãoNuvemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoNuvemButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botãoNuvemButton);
        botãoNuvemButton.setBounds(310, 220, 129, 122);

        botãoBananaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/banana.png"))); // NOI18N
        botãoBananaButton.setText("jToggleButton1");
        botãoBananaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoBananaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botãoBananaButton);
        botãoBananaButton.setBounds(450, 220, 129, 122);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/branco fundo.png"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 600, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botãoVermelhoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoVermelhoButtonActionPerformed
        boolean estavaResolvidoVerde = !(botãoVerdeButton.isEnabled());
        boolean estavaResolvidoAmarelo = !(botãoAmareloButton.isEnabled());
        boolean estavaResolvidoAzul = !(botãoAzulButton.isEnabled());
        if (botãoVermelhoButton.isSelected()) {
            botãoVermelhoButton.setBorder(BorderFactory.createLineBorder(Color.green, 5));
            System.out.println(botãoVerdeButton.isEnabled());
            if (!estavaResolvidoVerde) {
                System.out.println("Batata");
                botãoVerdeButton.setEnabled(false);
            }
            if (!estavaResolvidoAmarelo) {
                botãoAmareloButton.setEnabled(false);
            }
            if (!estavaResolvidoAzul) {
                botãoAzulButton.setEnabled(false);
            }
        }
        if (botãoVermelhoButton.isSelected()&& botãoMorangoButton.isSelected()){
            botãoVermelhoButton.setEnabled(false);
            botãoMorangoButton.setEnabled(false);
        } else {
            if (botãoPlantaButton.isSelected() || botãoNuvemButton.isSelected() || botãoBananaButton.isSelected()) {
                botãoPlantaButton.setSelected(false);
                botãoNuvemButton.setSelected(false);
                botãoBananaButton.setSelected(false);
                botãoVermelhoButton.setSelected(false);
                Usuario.pontuacao = Usuario.pontuacao - 25;
            }
        }
        if (!estavaResolvidoVerde) {
            botãoVerdeButton.setEnabled(true);
        }
        if (!estavaResolvidoAmarelo) {
            botãoAmareloButton.setEnabled(true);
        }
        if (!estavaResolvidoAzul) {
            botãoAzulButton.setEnabled(true);
        }
        verifica_fase();
    }//GEN-LAST:event_botãoVermelhoButtonActionPerformed

    private void botãoVerdeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoVerdeButtonActionPerformed
        boolean estavaResolvidoVermelho = !(botãoVermelhoButton.isEnabled());
        boolean estavaResolvidoAmarelo = !(botãoAmareloButton.isEnabled());
        boolean estavaResolvidoAzul = !(botãoAzulButton.isEnabled());
        if (botãoVerdeButton.isSelected()) {
            botãoVerdeButton.setBorder(BorderFactory.createLineBorder(Color.green, 5));
            if (!estavaResolvidoVermelho) {
                botãoVermelhoButton.setEnabled(false);
            }
            if (!estavaResolvidoAmarelo) {
                botãoAmareloButton.setEnabled(false);
            }
            if (!estavaResolvidoAzul) {
                botãoAzulButton.setEnabled(false);
            }
        }
        if (botãoVerdeButton.isSelected()&& botãoPlantaButton.isSelected()){
            botãoVerdeButton.setEnabled(false);
            botãoPlantaButton.setEnabled(false);
        } else {
            if (botãoMorangoButton.isSelected() || botãoNuvemButton.isSelected() || botãoBananaButton.isSelected()) {
                botãoMorangoButton.setSelected(false);
                botãoNuvemButton.setSelected(false);
                botãoBananaButton.setSelected(false);
                botãoVerdeButton.setSelected(false);
                Usuario.pontuacao = Usuario.pontuacao - 25;
            }
        }
        if (!estavaResolvidoVermelho) {
            botãoVermelhoButton.setEnabled(true);
        }
        if (!estavaResolvidoAmarelo) {
            botãoAmareloButton.setEnabled(true);
        }
        if (!estavaResolvidoAzul) {
            botãoAzulButton.setEnabled(true);

        } 
        verifica_fase();
    }//GEN-LAST:event_botãoVerdeButtonActionPerformed

    private void botãoAzulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoAzulButtonActionPerformed
        boolean estavaResolvidoVermelho = !(botãoVermelhoButton.isEnabled());
        boolean estavaResolvidoAmarelo = !(botãoAmareloButton.isEnabled());
        boolean estavaResolvidoVerde = !(botãoVerdeButton.isEnabled());
        if (botãoAzulButton.isSelected()) {
            botãoAzulButton.setBorder(BorderFactory.createLineBorder(Color.green, 5));
            if (!estavaResolvidoVermelho) {
                botãoVermelhoButton.setEnabled(false);
            }
            if (!estavaResolvidoAmarelo) {
                botãoAmareloButton.setEnabled(false);
            }
            if (!estavaResolvidoVerde) {
                botãoVerdeButton.setEnabled(false);
            }
        }
        if (botãoAzulButton.isSelected()&& botãoNuvemButton.isSelected()){
            botãoAzulButton.setEnabled(false);
            botãoNuvemButton.setEnabled(false);
        } else {
            if (botãoMorangoButton.isSelected() || botãoPlantaButton.isSelected() || botãoBananaButton.isSelected()) {
                botãoMorangoButton.setSelected(false);
                botãoPlantaButton.setSelected(false);
                botãoBananaButton.setSelected(false);
                botãoAzulButton.setSelected(false);
                Usuario.pontuacao = Usuario.pontuacao - 25;
            }
        }
        if (!estavaResolvidoVermelho) {
            botãoVermelhoButton.setEnabled(true);
        }
        if (!estavaResolvidoAmarelo) {
            botãoAmareloButton.setEnabled(true);
        }
        if (!estavaResolvidoVerde) {
            botãoVerdeButton.setEnabled(true);

        }  
        verifica_fase();
    }//GEN-LAST:event_botãoAzulButtonActionPerformed

    private void botãoAmareloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoAmareloButtonActionPerformed
        boolean estavaResolvidoVermelho = !(botãoVermelhoButton.isEnabled());
        boolean estavaResolvidoAzul = !(botãoAzulButton.isEnabled());
        boolean estavaResolvidoVerde = !(botãoVerdeButton.isEnabled());
        if (botãoAmareloButton.isSelected()) {
            botãoAmareloButton.setBorder(BorderFactory.createLineBorder(Color.green, 5));
            if (!estavaResolvidoVermelho) {
                botãoVermelhoButton.setEnabled(false);
            }
            if (!estavaResolvidoAzul) {
                botãoAzulButton.setEnabled(false);
            }
            if (!estavaResolvidoVerde) {
                botãoVerdeButton.setEnabled(false);
            }
        }
        if (botãoAmareloButton.isSelected()&& botãoBananaButton.isSelected()){
            botãoAmareloButton.setEnabled(false);
            botãoBananaButton.setEnabled(false);
        } else {
            if (botãoMorangoButton.isSelected() || botãoPlantaButton.isSelected() || botãoNuvemButton.isSelected()) {
                botãoMorangoButton.setSelected(false);
                botãoPlantaButton.setSelected(false);
                botãoNuvemButton.setSelected(false);
                botãoAmareloButton.setSelected(false);
                Usuario.pontuacao = Usuario.pontuacao - 25;
            }
        }
        if (!estavaResolvidoVermelho) {
            botãoVermelhoButton.setEnabled(true);
        }
        if (!estavaResolvidoAzul) {
            botãoAmareloButton.setEnabled(true);
        }
        if (!estavaResolvidoVerde) {
            botãoVerdeButton.setEnabled(true);
        }
        verifica_fase();
    }//GEN-LAST:event_botãoAmareloButtonActionPerformed

    private void botãoPlantaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoPlantaButtonActionPerformed
        boolean estavaResolvidoRespostaVermelho = !(botãoVermelhoButton.isEnabled());
        boolean estavaResolvidoRespostaAmarelo = !(botãoAmareloButton.isEnabled());
        boolean estavaResolvidoRespostaAzul = !(botãoAzulButton.isEnabled());
        if (botãoPlantaButton.isSelected()) {
            botãoPlantaButton.setBorder(BorderFactory.createLineBorder(Color.green, 5));
            if (!estavaResolvidoRespostaVermelho) {
                botãoMorangoButton.setEnabled(false);
            }
            if (!estavaResolvidoRespostaAmarelo) {
                botãoBananaButton.setEnabled(false);
            }
            if (!estavaResolvidoRespostaAzul) {
                botãoNuvemButton.setEnabled(false);
            }
        }
        if (botãoPlantaButton.isSelected()&& botãoVerdeButton.isSelected()){
            botãoVerdeButton.setEnabled(false);
            botãoPlantaButton.setEnabled(false);
        } else {
            if (botãoVermelhoButton.isSelected() || botãoAzulButton.isSelected() || botãoAmareloButton.isSelected()) {
                botãoVermelhoButton.setSelected(false);
                botãoAzulButton.setSelected(false);
                botãoAmareloButton.setSelected(false);
                botãoPlantaButton.setSelected(false);
                Usuario.pontuacao = Usuario.pontuacao - 25;
            }
        }
        if (!estavaResolvidoRespostaVermelho) {
            botãoVermelhoButton.setEnabled(true);
        }
        if (!estavaResolvidoRespostaAmarelo) {
            botãoAmareloButton.setEnabled(true);
        }
        if (!estavaResolvidoRespostaAzul) {
            botãoAzulButton.setEnabled(true);
            
        } 
        verifica_fase();
    }//GEN-LAST:event_botãoPlantaButtonActionPerformed

    private void botãoMorangoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoMorangoButtonActionPerformed
         boolean estavaResolvidoRespostaVerde = !(botãoPlantaButton.isEnabled());
        boolean estavaResolvidoRespostaAmarelo = !(botãoBananaButton.isEnabled());
        boolean estavaResolvidoRespostaAzul = !(botãoNuvemButton.isEnabled());
        if (botãoMorangoButton.isSelected()) {
            botãoMorangoButton.setBorder(BorderFactory.createLineBorder(Color.green, 5));
            if (!estavaResolvidoRespostaVerde) {
                botãoPlantaButton.setEnabled(false);
            }
            if (!estavaResolvidoRespostaAmarelo) {
                botãoBananaButton.setEnabled(false);
            }
            if (!estavaResolvidoRespostaAzul) {
                botãoNuvemButton.setEnabled(false);
            }
        }
        if (botãoMorangoButton.isSelected()&& botãoVermelhoButton.isSelected()){
            botãoVermelhoButton.setEnabled(false);
            botãoMorangoButton.setEnabled(false);
        } else {
            if (botãoVerdeButton.isSelected() || botãoAzulButton.isSelected() || botãoAmareloButton.isSelected()) {
                botãoVerdeButton.setSelected(false);
                botãoAzulButton.setSelected(false);
                botãoAmareloButton.setSelected(false);
                botãoMorangoButton.setSelected(false);
                Usuario.pontuacao = Usuario.pontuacao - 25;
            }
        }
        if (!estavaResolvidoRespostaVerde) {
            botãoVerdeButton.setEnabled(true);
        }
        if (!estavaResolvidoRespostaAmarelo) {
            botãoAmareloButton.setEnabled(true);
        }
        if (!estavaResolvidoRespostaAzul) {
            botãoAzulButton.setEnabled(true);
        }
        verifica_fase();
    }//GEN-LAST:event_botãoMorangoButtonActionPerformed

    private void botãoNuvemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoNuvemButtonActionPerformed
        boolean estavaResolvidoRespostaVerde = !(botãoPlantaButton.isEnabled());
        boolean estavaResolvidoRespostaAmarelo = !(botãoBananaButton.isEnabled());
        boolean estavaResolvidoRespostaVermelho = !(botãoMorangoButton.isEnabled());
        if (botãoNuvemButton.isSelected()) {
            botãoNuvemButton.setBorder(BorderFactory.createLineBorder(Color.green, 5));
            if (!estavaResolvidoRespostaVerde) {
                botãoPlantaButton.setEnabled(false);
            }
            if (!estavaResolvidoRespostaAmarelo) {
                botãoBananaButton.setEnabled(false);
            }
            if (!estavaResolvidoRespostaVermelho) {
                botãoMorangoButton.setEnabled(false);
            }
        }
        if (botãoNuvemButton.isSelected()&& botãoAzulButton.isSelected()){
            botãoAzulButton.setEnabled(false);
            botãoNuvemButton.setEnabled(false);
        } else {
            if (botãoVerdeButton.isSelected() || botãoVermelhoButton.isSelected() || botãoAmareloButton.isSelected()) {
                botãoVerdeButton.setSelected(false);
                botãoVermelhoButton.setSelected(false);
                botãoAmareloButton.setSelected(false);
                botãoNuvemButton.setSelected(false);
                Usuario.pontuacao = Usuario.pontuacao - 25;
            }
        }
        if (!estavaResolvidoRespostaVerde) {
            botãoVerdeButton.setEnabled(true);
        }
        if (!estavaResolvidoRespostaAmarelo) {
            botãoAmareloButton.setEnabled(true);
        }
        if (!estavaResolvidoRespostaVermelho) {
            botãoAzulButton.setEnabled(true);
        }
        verifica_fase();
    }//GEN-LAST:event_botãoNuvemButtonActionPerformed

    private void botãoBananaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoBananaButtonActionPerformed
        boolean estavaResolvidoRespostaVerde = !(botãoPlantaButton.isEnabled());
        boolean estavaResolvidoRespostaVermelho = !(botãoMorangoButton.isEnabled());
        boolean estavaResolvidoRespostaAzul = !(botãoNuvemButton.isEnabled());
        if (botãoBananaButton.isSelected()) {
            botãoBananaButton.setBorder(BorderFactory.createLineBorder(Color.green, 5));
            if (!estavaResolvidoRespostaVerde) {
                botãoPlantaButton.setEnabled(false);
            }
            if (!estavaResolvidoRespostaVermelho) {
                botãoMorangoButton.setEnabled(false);
            }
            if (!estavaResolvidoRespostaAzul) {
                botãoNuvemButton.setEnabled(false);
            }
        }
        if (botãoBananaButton.isSelected()&& botãoAmareloButton.isSelected()){
            botãoAmareloButton.setEnabled(false);
            botãoBananaButton.setEnabled(false);
        } else {
            if (botãoVerdeButton.isSelected() || botãoAzulButton.isSelected() || botãoVermelhoButton.isSelected()) {
                botãoVerdeButton.setSelected(false);
                botãoAzulButton.setSelected(false);
                botãoVermelhoButton.setSelected(false);
                botãoBananaButton.setSelected(false);
                Usuario.pontuacao = Usuario.pontuacao - 25;
            }
        }
        if (!estavaResolvidoRespostaVerde) {
            botãoVerdeButton.setEnabled(true);
        }
        if (!estavaResolvidoRespostaVermelho) {
            botãoVermelhoButton.setEnabled(true);
        }
        if (!estavaResolvidoRespostaAzul) {
            botãoAzulButton.setEnabled(true);
        }
        verifica_fase();
    }//GEN-LAST:event_botãoBananaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fase1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JToggleButton botãoAmareloButton;
    private javax.swing.JToggleButton botãoAzulButton;
    private javax.swing.JToggleButton botãoBananaButton;
    private javax.swing.JToggleButton botãoMorangoButton;
    private javax.swing.JToggleButton botãoNuvemButton;
    private javax.swing.JToggleButton botãoPlantaButton;
    private javax.swing.JToggleButton botãoVerdeButton;
    private javax.swing.JToggleButton botãoVermelhoButton;
    // End of variables declaration//GEN-END:variables
}
