
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.t2._maua_tti101_t2_sistema_academico.telas;

import br.maua.t2._maua_tti101_t2_sistema_academico.modelo.Usuario;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author luisa
 */
public class Fase4 extends javax.swing.JFrame {
int selecionado = -1; 
boolean botao_g = false;//0
boolean botao_m = false;
boolean botao_e = false;
boolean botao_c = false;
boolean gato = false;
boolean maca = false;
boolean elefante = false;
boolean coracao = false;
public void verificar_estado(){
    if (botao_g) {
        botaoGButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoGButton.setEnabled(false);
    }
    if (botao_m) {
        botaoMButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoMButton.setEnabled(false);
    }
    if (botao_e) {
        botaoEButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoEButton.setEnabled(false);
    }
    if (botao_c) {
        botaoCButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoCButton.setEnabled(false);
    }
    if (gato) {
        botaoGataButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoGataButton.setEnabled(false);
    }
    if (maca) {
        botaoMacaButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoMacaButton.setEnabled(false);
    }
    if (elefante) {
        botaoElefanteButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoElefanteButton.setEnabled(false);
    }
    if (coracao) {
        botaoCoracaoButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoCoracaoButton.setEnabled(false);
    }
}
public void verifica_fase(){
    if ((botao_g && !gato) || (botao_m && !maca)|| (botao_e && !elefante) || (botao_c && !coracao)) {
        Usuario.pontuacao = Usuario.pontuacao - 25;
    }
}
    /**
     * Creates new form Fase4
     */
    public Fase4() {
        initComponents();
    }
    
    private boolean avaliarSelecionado(int valor){
        
        if (selecionado == -1){
            selecionado = valor;
            return false;
        }
        //este primeiro if está verificando se ele foi selecionado, e apenas ele.
        else if (valor %4 == selecionado %4 && valor != selecionado){
            return true;
        //este if verifica se os dois valores lógicos são iguais(selecionado e valor atual). caso sim, o valor ficará verdadeiro.
        }
        else {
            selecionado = -1;
            return false;
        }
        //se o segundo botão for selecionado errado, ele volta a lógica dos botões para o estado inicial.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCoracaoButton = new javax.swing.JToggleButton();
        botaoMacaButton = new javax.swing.JToggleButton();
        botaoElefanteButton = new javax.swing.JToggleButton();
        botaoGataButton = new javax.swing.JToggleButton();
        botaoMButton = new javax.swing.JToggleButton();
        botaoGButton = new javax.swing.JToggleButton();
        botaoCButton = new javax.swing.JToggleButton();
        botaoEButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(610, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        botaoCoracaoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coracao.png"))); // NOI18N
        botaoCoracaoButton.setText("jToggleButton1");
        botaoCoracaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCoracaoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCoracaoButton);
        botaoCoracaoButton.setBounds(453, 75, 129, 122);

        botaoMacaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/maça.png"))); // NOI18N
        botaoMacaButton.setText("jToggleButton1");
        botaoMacaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMacaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMacaButton);
        botaoMacaButton.setBounds(306, 75, 129, 122);

        botaoElefanteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/elefante.png"))); // NOI18N
        botaoElefanteButton.setText("jToggleButton1");
        botaoElefanteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoElefanteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoElefanteButton);
        botaoElefanteButton.setBounds(159, 75, 129, 122);

        botaoGataButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gato.png"))); // NOI18N
        botaoGataButton.setText("jToggleButton1");
        botaoGataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGataButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoGataButton);
        botaoGataButton.setBounds(18, 74, 129, 123);

        botaoMButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/letram.png"))); // NOI18N
        botaoMButton.setText("jToggleButton1");
        botaoMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMButton);
        botaoMButton.setBounds(455, 242, 129, 122);

        botaoGButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/letrag.png"))); // NOI18N
        botaoGButton.setText("jToggleButton1");
        botaoGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoGButton);
        botaoGButton.setBounds(308, 242, 129, 122);

        botaoCButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/letraC.png"))); // NOI18N
        botaoCButton.setText("jToggleButton1");
        botaoCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCButton);
        botaoCButton.setBounds(159, 242, 129, 122);

        botaoEButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/letraE.png"))); // NOI18N
        botaoEButton.setText("jToggleButton1");
        botaoEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoEButton);
        botaoEButton.setBounds(18, 242, 129, 122);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/branco fundo.png"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCoracaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCoracaoButtonActionPerformed
        //coracao
        int valor = 3;
        if (!coracao && !botao_c && avaliarSelecionado(valor)){
            coracao = true;
            botao_c = true;
            verificar_estado();
        }  
        verifica_fase();
    }//GEN-LAST:event_botaoCoracaoButtonActionPerformed

    private void botaoMacaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMacaButtonActionPerformed
        //maca
        int valor = 2;
        if (!maca && !botao_m && avaliarSelecionado(valor)){
            maca = true;
            botao_m = true;
            verificar_estado();
        } 
        verifica_fase();
    }//GEN-LAST:event_botaoMacaButtonActionPerformed

    private void botaoElefanteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoElefanteButtonActionPerformed
        // elefante
        int valor = 1;
        if (!elefante && !botao_e && avaliarSelecionado(valor)){
            elefante = true;
            botao_e = true;
            verificar_estado();       
        }   
        verifica_fase();
    }//GEN-LAST:event_botaoElefanteButtonActionPerformed

    private void botaoGataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGataButtonActionPerformed
        // gato
        int valor = 0;
        if (!gato && !botao_g && avaliarSelecionado(valor)){
            gato = true;
            botao_g = true;
            verificar_estado();
        }  
        verifica_fase();
    }//GEN-LAST:event_botaoGataButtonActionPerformed

    private void botaoMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMButtonActionPerformed
        //m
        int valor = 6;
        if (!maca && !botao_m && avaliarSelecionado(valor)){
            maca = true;
            botao_m = true;
            verificar_estado();
        }  
        verifica_fase();
    }//GEN-LAST:event_botaoMButtonActionPerformed

    private void botaoGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGButtonActionPerformed
        //g
        int valor = 4;
        if (!gato && !botao_g && avaliarSelecionado(valor)){
            gato = true;
            botao_g = true;
            verificar_estado();
        }  
        verifica_fase();
    }//GEN-LAST:event_botaoGButtonActionPerformed

    private void botaoCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCButtonActionPerformed
        //c
        int valor = 7;
        if (!coracao && !botao_c && avaliarSelecionado(valor)){
            coracao = true;
            botao_c = true;
            verificar_estado();
        } 
        verifica_fase();
    }//GEN-LAST:event_botaoCButtonActionPerformed

    private void botaoEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEButtonActionPerformed
        //e
        int valor = 5;
        if (!elefante && !botao_e && avaliarSelecionado(valor)){
            elefante = true;
            botao_e = true;
            verificar_estado();
        } 
        verifica_fase();
    }//GEN-LAST:event_botaoEButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fase4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fase4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fase4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fase4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fase4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoCButton;
    private javax.swing.JToggleButton botaoCoracaoButton;
    private javax.swing.JToggleButton botaoEButton;
    private javax.swing.JToggleButton botaoElefanteButton;
    private javax.swing.JToggleButton botaoGButton;
    private javax.swing.JToggleButton botaoGataButton;
    private javax.swing.JToggleButton botaoMButton;
    private javax.swing.JToggleButton botaoMacaButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
