
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.t2._maua_tti101_t2_sistema_academico.telas;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author luisa
 */
public class Fase4 extends javax.swing.JFrame {
int selecionado = -1; 
boolean botao_g = false;//0
boolean botao_m = false;
boolean botao_e = false;
boolean botao_c = false;
boolean gato = false;
boolean maca = false;
boolean elefante = false;
boolean coracao = false;
public void verificar_estado(){
    if (botao_g) {
        jToggleButton6.setBorder(BorderFactory.createLineBorder(Color.green));
        jToggleButton6.setEnabled(false);
    }
    if (botao_m) {
        jToggleButton5.setBorder(BorderFactory.createLineBorder(Color.green));
        jToggleButton5.setEnabled(false);
    }
    if (botao_e) {
        jToggleButton2.setBorder(BorderFactory.createLineBorder(Color.green));
        jToggleButton2.setEnabled(false);
    }
    if (botao_c) {
        jToggleButton7.setBorder(BorderFactory.createLineBorder(Color.green));
        jToggleButton7.setEnabled(false);
    }
    if (gato) {
        jToggleButton4.setBorder(BorderFactory.createLineBorder(Color.green));
        jToggleButton4.setEnabled(false);
    }
    if (maca) {
        jToggleButton2.setBorder(BorderFactory.createLineBorder(Color.green));
        jToggleButton2.setEnabled(false);
    }
    if (elefante) {
        jToggleButton3.setBorder(BorderFactory.createLineBorder(Color.green));
        jToggleButton3.setEnabled(false);
    }
    if (coracao) {
        jToggleButton1.setBorder(BorderFactory.createLineBorder(Color.green));
        jToggleButton1.setEnabled(false);
    }
}

    /**
     * Creates new form Fase4
     */
    public Fase4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\20241_maua_tti101_t2_sistema_academico\\src\\main\\images\\heart.png")); // NOI18N
        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(453, 75, 129, 122);

        jToggleButton2.setIcon(new javax.swing.ImageIcon("C:\\20241_maua_tti101_t2_sistema_academico\\src\\main\\images\\maçç.png")); // NOI18N
        jToggleButton2.setText("jToggleButton1");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(306, 75, 129, 122);

        jToggleButton3.setIcon(new javax.swing.ImageIcon("C:\\20241_maua_tti101_t2_sistema_academico\\src\\main\\images\\ele.png")); // NOI18N
        jToggleButton3.setText("jToggleButton1");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3);
        jToggleButton3.setBounds(159, 75, 129, 122);

        jToggleButton4.setIcon(new javax.swing.ImageIcon("C:\\20241_maua_tti101_t2_sistema_academico\\src\\main\\images\\cat.png")); // NOI18N
        jToggleButton4.setText("jToggleButton1");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton4);
        jToggleButton4.setBounds(18, 74, 129, 123);

        jToggleButton5.setIcon(new javax.swing.ImageIcon("C:\\20241_maua_tti101_t2_sistema_academico\\src\\main\\images\\mmm.png")); // NOI18N
        jToggleButton5.setText("jToggleButton1");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton5);
        jToggleButton5.setBounds(455, 242, 129, 122);

        jToggleButton6.setIcon(new javax.swing.ImageIcon("C:\\20241_maua_tti101_t2_sistema_academico\\src\\main\\images\\ggg.png")); // NOI18N
        jToggleButton6.setText("jToggleButton1");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton6);
        jToggleButton6.setBounds(308, 242, 129, 122);

        jToggleButton7.setIcon(new javax.swing.ImageIcon("C:\\20241_maua_tti101_t2_sistema_academico\\src\\main\\images\\ccc.png")); // NOI18N
        jToggleButton7.setText("jToggleButton1");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton7);
        jToggleButton7.setBounds(159, 242, 129, 122);

        jToggleButton8.setIcon(new javax.swing.ImageIcon("C:\\20241_maua_tti101_t2_sistema_academico\\src\\main\\images\\eee.png")); // NOI18N
        jToggleButton8.setText("jToggleButton1");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton8);
        jToggleButton8.setBounds(18, 242, 129, 122);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\20241_maua_tti101_t2_sistema_academico\\src\\main\\images\\branco fundo.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-3, -5, 610, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        //coracao
        int valor = 3;
        if (selecionado == -1)
            selecionado = valor%4;
        else if (selecionado != 3|| coracao )
            selecionado = -1;
        else {
            coracao = true;
            botao_c = true;
            verificar_estado();
        }                        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        //maca
        int valor = 2;
        if (selecionado == -1)
            selecionado = valor%4;
        else if (selecionado != 2|| maca )
            selecionado = -1;
        else {
            maca = true;
            botao_m = true;
            verificar_estado();
        }                         
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // elefante
        int valor = 1;
        if (selecionado == -1)
            selecionado = valor%4;
        else if (selecionado != 1 || elefante )
            selecionado = -1;
        else {
            elefante = true;
            botao_e = true;
            verificar_estado();
        }    
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // gato
        int valor = 0;
        if (selecionado == -1)
            selecionado = valor%4;
        else if (selecionado != 0 || gato)
            selecionado = -1;
        else {
            gato = true;
            botao_g = true;
            verificar_estado();
        }    
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        //m
        int valor = 6;
        if (selecionado == -1)
            selecionado = valor%4;
        else if (selecionado != 6|| botao_m )
            selecionado = -1;
        else {
            botao_m = true;
            maca = true;
            verificar_estado();
        }                        
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        //g
        int valor = 4;
        if (selecionado == -1)
            selecionado = valor%4;
        else if (selecionado != 4|| botao_g )
            selecionado = -1;
        else {
            botao_g = true;
            gato = true;
            verificar_estado();
        }                        
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        //c
        int valor = 7;
        if (selecionado == -1)
            selecionado = valor%4;
        else if (selecionado != 7|| botao_c )
            selecionado = -1;
        else {
            botao_c = true;
            coracao = true;
            verificar_estado();
        }                        
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        //e
        int valor = 5;
        if (selecionado == -1)
            selecionado = valor%4;
        else if (selecionado != 5|| botao_e )
            selecionado = -1;
        else {
            botao_e = true;
            elefante = true;
            verificar_estado();
        }                        
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fase4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fase4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fase4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fase4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fase4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    // End of variables declaration//GEN-END:variables
}
