/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.t2._maua_tti101_t2_sistema_academico.telas;

import br.maua.t2._maua_tti101_t2_sistema_academico.modelo.Usuario;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author luisa
 */
public class Fase2 extends javax.swing.JFrame {
int selecionado = -1; 
boolean botao_um = false;//0
boolean botao_dois = false;
boolean botao_tres = false;
boolean botao_quatro = false;
boolean uma_mochila = false;
boolean dois_lapis = false;
boolean tres_livros = false;
boolean quatro_borrachas = false;
public void verificar_estado(){
    if (botao_um) {
        botaoUmButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoUmButton.setEnabled(false);
    }
    if (uma_mochila) {
        botaoMochilaButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoMochilaButton.setEnabled(false);
    }
    if (botao_dois) {
        botaoDoisButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoDoisButton.setEnabled(false);
    }
    if (dois_lapis) {
        botaoLapisButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoLapisButton.setEnabled(false);
    }
    if (botao_tres) {
        botaoTresButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoTresButton.setEnabled(false);
    }
    if (tres_livros) {
        botaoLivrosButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoLivrosButton.setEnabled(false);
    }
    if (botao_quatro) {
        botaoQuatroButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoQuatroButton.setEnabled(false);
    }
    if (quatro_borrachas) {
        botaoBorrachasButton.setBorder(BorderFactory.createLineBorder(Color.green));
        botaoBorrachasButton.setEnabled(false);
    }
}
public void verifica_fase(){
    if ((botao_um && !uma_mochila) || (botao_dois && !dois_lapis)|| (botao_tres && !tres_livros) || (botao_quatro && !quatro_borrachas)) {
        Usuario.pontuacao = Usuario.pontuacao - 25;
    }
}
    /**
     * Creates new form Fase2
     */
    public Fase2() {
        initComponents();
    }
    
    private boolean avaliarSelecionado(int valor){
        
        if (selecionado == -1){
            selecionado = valor;
            return false;
        }
        //este primeiro if está verificando se ele foi selecionado, e apenas ele.
        else if (valor %4 == selecionado %4 && valor != selecionado){
            return true;
        //este if verifica se os dois valores lógicos são iguais(selecionado e valor atual). caso sim, o valor ficará verdadeiro.
        }
        else {
            selecionado = -1;
            return false;
        }
        //se o segundo botão for selecionado errado, ele volta a lógica dos botões para o estado inicial.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoLivrosButton = new javax.swing.JToggleButton();
        botaoTresButton = new javax.swing.JToggleButton();
        botaoDoisButton = new javax.swing.JToggleButton();
        botaoUmButton = new javax.swing.JToggleButton();
        botaoMochilaButton = new javax.swing.JToggleButton();
        botaoLapisButton = new javax.swing.JToggleButton();
        botaoBorrachasButton = new javax.swing.JToggleButton();
        botaoQuatroButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botaoLivrosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/treslivros.png"))); // NOI18N
        botaoLivrosButton.setText("jToggleButton1");
        botaoLivrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLivrosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoLivrosButton);
        botaoLivrosButton.setBounds(450, 240, 129, 122);

        botaoTresButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/numero3.png"))); // NOI18N
        botaoTresButton.setText("jToggleButton1");
        botaoTresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTresButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoTresButton);
        botaoTresButton.setBounds(310, 60, 130, 122);

        botaoDoisButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/numero2.png"))); // NOI18N
        botaoDoisButton.setText("jToggleButton1");
        botaoDoisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDoisButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoDoisButton);
        botaoDoisButton.setBounds(160, 60, 129, 122);

        botaoUmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/numero1.png"))); // NOI18N
        botaoUmButton.setText("jToggleButton1");
        botaoUmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoUmButton);
        botaoUmButton.setBounds(20, 60, 129, 122);

        botaoMochilaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mochila.png"))); // NOI18N
        botaoMochilaButton.setText("jToggleButton1");
        botaoMochilaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMochilaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMochilaButton);
        botaoMochilaButton.setBounds(160, 240, 129, 122);

        botaoLapisButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/doislapis.png"))); // NOI18N
        botaoLapisButton.setText("jToggleButton1");
        botaoLapisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLapisButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoLapisButton);
        botaoLapisButton.setBounds(310, 240, 129, 120);

        botaoBorrachasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quatroborrachas.png"))); // NOI18N
        botaoBorrachasButton.setText("jToggleButton1");
        botaoBorrachasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBorrachasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoBorrachasButton);
        botaoBorrachasButton.setBounds(10, 240, 129, 122);

        botaoQuatroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/numeoro4.png"))); // NOI18N
        botaoQuatroButton.setText("jToggleButton1");
        botaoQuatroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoQuatroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(botaoQuatroButton);
        botaoQuatroButton.setBounds(450, 60, 129, 122);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/branco fundo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLivrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLivrosButtonActionPerformed
        //três livros
        int valor = 6;
        if (!tres_livros && !botao_tres && avaliarSelecionado(valor)){
            tres_livros = true;
            botao_tres = true;
            verificar_estado();
        }
        verifica_fase();
    }//GEN-LAST:event_botaoLivrosButtonActionPerformed

    private void botaoTresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTresButtonActionPerformed
        //três
        int valor = 2;
        if (!tres_livros && !botao_tres && avaliarSelecionado(valor)){
            tres_livros = true;
            botao_tres = true;
            verificar_estado();
        }
        verifica_fase();
    }//GEN-LAST:event_botaoTresButtonActionPerformed

    private void botaoDoisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDoisButtonActionPerformed
        //dois
         int valor = 1;
        if (!botao_dois && !dois_lapis && avaliarSelecionado(valor)){
            botao_dois = true;
            dois_lapis = true;
            verificar_estado();
        } 
        verifica_fase();
    }//GEN-LAST:event_botaoDoisButtonActionPerformed

    private void botaoUmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUmButtonActionPerformed
        //um
        int valor = 0;
        if (!botao_um && !uma_mochila && avaliarSelecionado(valor)){
            botao_um = true;
            uma_mochila = true;
            verificar_estado();
        } 
        verifica_fase();
    }//GEN-LAST:event_botaoUmButtonActionPerformed

    private void botaoMochilaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMochilaButtonActionPerformed
        //uma mochila
        int valor = 4;
        if (!botao_um && !uma_mochila && avaliarSelecionado(valor)){
            botao_um = true;
            uma_mochila = true;
            verificar_estado();
        }
        verifica_fase();
    }//GEN-LAST:event_botaoMochilaButtonActionPerformed

    private void botaoLapisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLapisButtonActionPerformed
        //dois lápis
        int valor = 5;
        if (!botao_dois && !dois_lapis && avaliarSelecionado(valor)){
            botao_dois = true;
            dois_lapis = true;
            verificar_estado();
        }
        verifica_fase();
    }//GEN-LAST:event_botaoLapisButtonActionPerformed

    private void botaoBorrachasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBorrachasButtonActionPerformed
        //quatro borrachas
        int valor = 7;
        if (!botao_quatro && !quatro_borrachas && avaliarSelecionado(valor)){
            botao_quatro = true;
            quatro_borrachas = true;
            verificar_estado();
        }
        verifica_fase();
    }//GEN-LAST:event_botaoBorrachasButtonActionPerformed

    private void botaoQuatroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoQuatroButtonActionPerformed
        //quatro
        int valor = 3;
        if (!botao_quatro && !quatro_borrachas && avaliarSelecionado(valor)){
            botao_quatro = true;
            quatro_borrachas = true;
            verificar_estado();
        }  
        verifica_fase();
    }//GEN-LAST:event_botaoQuatroButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fase2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoBorrachasButton;
    private javax.swing.JToggleButton botaoDoisButton;
    private javax.swing.JToggleButton botaoLapisButton;
    private javax.swing.JToggleButton botaoLivrosButton;
    private javax.swing.JToggleButton botaoMochilaButton;
    private javax.swing.JToggleButton botaoQuatroButton;
    private javax.swing.JToggleButton botaoTresButton;
    private javax.swing.JToggleButton botaoUmButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
