/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.t2._maua_tti101_t2_sistema_academico.telas;

import br.maua.t2._maua_tti101_t2_sistema_academico.modelo.Usuario;
import br.maua.t2._maua_tti101_t2_sistema_academico.db.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author luisa
 */
public class LoginTela extends javax.swing.JFrame {

    /**
     * Creates new form LoginTela
     */
    public LoginTela() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        digiteSeuLoginButton = new javax.swing.JTextField();
        digiteSuaSenhaButton = new javax.swing.JPasswordField();
        convidadoButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        cadastrarButton = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(610, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(610, 480));
        getContentPane().setLayout(null);

        digiteSeuLoginButton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Digite seu Login:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        digiteSeuLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digiteSeuLoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(digiteSeuLoginButton);
        digiteSeuLoginButton.setBounds(20, 20, 560, 70);

        digiteSuaSenhaButton.setForeground(new java.awt.Color(0, 142, 246));
        digiteSuaSenhaButton.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Digite sua senha:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        digiteSuaSenhaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digiteSuaSenhaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(digiteSuaSenhaButton);
        digiteSuaSenhaButton.setBounds(20, 100, 560, 70);

        convidadoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        convidadoButton.setText("Convidado");
        convidadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convidadoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(convidadoButton);
        convidadoButton.setBounds(310, 300, 270, 80);

        okButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);
        okButton.setBounds(180, 190, 240, 80);

        cadastrarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarButton.setText("Não tem login: Criar conta");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarButton);
        cadastrarButton.setBounds(20, 300, 260, 80);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela azul.jpg"))); // NOI18N
        fundo.setName(""); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 610, 460);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(410, 190, 10, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void digiteSeuLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digiteSeuLoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digiteSeuLoginButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        Usuario.Fase1 = false;
        Usuario.Fase2 = false;
        Usuario.Fase3 = false;
        Usuario.Fase4 = false;
        Usuario.pontuacao = 1000;
      try{
        //1. pegar o login digitado pelo usuario
        var login = digiteSeuLoginButton.getText();
        //2. pegar a senha digitada pelo usuario
        var senha = new String(digiteSuaSenhaButton.getPassword());
        //3. verificar se ele digitou admin/admin
        var usuario = new Usuario();
        usuario.setLogin(login);
        usuario.setSenha(senha);
        var dao = new UsuarioDAO();
        if(dao.existe(usuario)){//verifica se existe o usuario
            if (dao.verificaProfessor(usuario)){
                dispose();
                new PontuacaoProfessor().setVisible(true);
            } 
            else{
                dispose();
                new TelaFasess().setVisible(true);
            }
        
        }
        else{
        JOptionPane.showMessageDialog(null, "Este usuário não existe");       
        }
            
      }
      catch(Exception e){
            System.out.println(e);
      }
        
        
    try {
    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (Exception e) {
    // Lidar com exceções, se necessário
    e.printStackTrace();
}
    }//GEN-LAST:event_okButtonActionPerformed

    private void convidadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convidadoButtonActionPerformed
        Usuario.pontuacao = 1000;
        Usuario.Fase1 = false;
        Usuario.Fase2 = false;
        Usuario.Fase3 = false;
        Usuario.Fase4 = false;
        Usuario.login = "Convidado";
        dispose();
        new TelaFasess().setVisible(true);
        
    }//GEN-LAST:event_convidadoButtonActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        var ctt = new CadastroTurmaTela();
        ctt.setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void digiteSuaSenhaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digiteSuaSenhaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digiteSuaSenhaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTela().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JButton convidadoButton;
    private javax.swing.JTextField digiteSeuLoginButton;
    private javax.swing.JPasswordField digiteSuaSenhaButton;
    private javax.swing.JLabel fundo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
