/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.t2._maua_tti101_t2_sistema_academico.telas;
import br.maua.t2._maua_tti101_t2_sistema_academico.db.UsuarioDAO;
import br.maua.t2._maua_tti101_t2_sistema_academico.db.ConnectionFactory;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author luisa
 */
public class PontuacaoProfessor extends javax.swing.JFrame {

    // Method to fetch data from the database
private List<Object[]> fetchData() throws Exception {
    List<Object[]> data = new ArrayList<>();
    
    // SQL query to fetch data
    String sql = "SELECT u.NOME, p.PONTUACAO, p.DIA_HORARIO FROM PONTUACAO p JOIN USUARIOS u ON p.ID_USUARIO = u.ID_USUARIO";
    
    // Establish a connection with the database
    Connection conexao = new ConnectionFactory().obterConexao();
    PreparedStatement ps = conexao.prepareStatement(sql);
    ResultSet rs = ps.executeQuery();
    
    // Fetch the data
    while (rs.next()) {
        String nome = rs.getString("NOME");
        int pontuacao = rs.getInt("PONTUACAO");
        Timestamp dataHora = rs.getTimestamp("DIA_HORARIO");
        data.add(new Object[]{nome, pontuacao, dataHora});
    }
    
    // Close the connection
    rs.close();
    ps.close();
    conexao.close();
    
    return data;
}

// Method to populate the JTable
public void populateTable(JTable table) throws Exception {
    // Fetch data
    List<Object[]> data = fetchData();
    
    // Column names
    String[] columnNames = {"Nome", "Pontuação", "Data/Hora"};
    
    // Create table model
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);
    
    // Add rows to the table model
    for (Object[] row : data) {
        model.addRow(row);
    }
    
    // Set the model to the table
    table.setModel(model);
}
    
    /**
     * Creates new form PontuacaoProfessor
     * @throws java.lang.Exception
     */
    public PontuacaoProfessor() throws Exception{
        initComponents();
        var dao = new UsuarioDAO();
        String[] turmas = dao.getTurmas();
        for ( String turma: turmas){
            escolherSalasButton.addItem(turma);
        }
        populateTable(tabelaDoProfessor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDoProfessor = new javax.swing.JTable();
        escolherSalasButton = new javax.swing.JComboBox<>();
        TurmaLabel = new javax.swing.JLabel();
        pesquisarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaDoProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome ", "Pontuação", "Data/Hora"
            }
        ));
        jScrollPane1.setViewportView(tabelaDoProfessor);

        escolherSalasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolherSalasButtonActionPerformed(evt);
            }
        });

        TurmaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TurmaLabel.setText("Turmas:");

        pesquisarButton.setText("Pesquisar");
        pesquisarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TurmaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escolherSalasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escolherSalasButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TurmaLabel)
                    .addComponent(pesquisarButton))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escolherSalasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolherSalasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escolherSalasButtonActionPerformed

    private void pesquisarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarButtonActionPerformed
    // Get the selected value from the combo box
    String turma = escolherSalasButton.getSelectedItem().toString();

    if (!"".equals(turma)) {
        try {
            var dao = new UsuarioDAO();
            // Assuming buscarTurma method returns a List<Object[]> containing data
            String[][] data = dao.buscarTurma(turma);

            // Clear existing table data
            DefaultTableModel model = (DefaultTableModel) tabelaDoProfessor.getModel();
            model.setRowCount(0);

            // Add fetched data to the table
            for (Object[] row : data) {
                model.addRow(row);
            }
        } catch (Exception ex) {
            Logger.getLogger(PontuacaoProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        // Handle empty selection
    }
    }//GEN-LAST:event_pesquisarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PontuacaoProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PontuacaoProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PontuacaoProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PontuacaoProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PontuacaoProfessor().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(PontuacaoProfessor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TurmaLabel;
    private javax.swing.JComboBox<String> escolherSalasButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pesquisarButton;
    private javax.swing.JTable tabelaDoProfessor;
    // End of variables declaration//GEN-END:variables
}
